version: "2"

services: 
  couchdb:
    container_name: couchdb
    image: couchdb:3.1
    environment: 
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports: 
      - 5984:5984
    volumes: 
      - ./data:/opt/couchdb/data
