version: 1.0.0

client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'

organizations:
  Org1:
    mspid: Org1MSP
    cryptoPath: ~/Develop/Blockchain/fabric-cases/devnet/organizations/peerOrganizations/org1.develop.com/users/{username}@org1.develop.com/msp
    peers:
      - peer0.org1.develop.com
    certificateAuthorities:
      - ca.org1.develop.com

orderers:
  orderer.develop.com:
    url: orderer.develop.com:7050
    grpcOptions:
    tlsCACerts:
      path: ../../devnet/organizations/fabric-ca/ordererOrg/ca-cert.pem

peers:
  peer0.org1.develop.com:
    url: peer0.org1.develop.com:7051
    tlsCACerts:
      path: ../../devnet/organizations/peerOrganizations/org1.develop.com/tlsca/tlsca.org1.develop.com-cert.pem

certificateAuthorities:
  ca.org1.develop.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      path: ../../devnet/organizations/peerOrganizations/org1.develop.com/ca/ca.org1.develop.com-cert.pem

entityMatchers:
  orderer:
    - pattern: (\w+).develop.(\w+)
      urlSubstitutionExp: localhost:7050
      sslTargetOverrideUrlSubstitutionExp: orderer.develop.com
      mappedHost: orderer.develop.com

    - pattern: (\w+).develop.(\w+):(\d+)
      urlSubstitutionExp: localhost:7050
      sslTargetOverrideUrlSubstitutionExp: orderer.develop.com
      mappedHost: orderer.develop.com